### ISSUE TITLE
Problem with the connector.

### ISSUE THREAD

**Issue by juliecrampe** [przemoo83/Google-Trends-DSC#1]
I have the following error:
Unexpected token C in JSON at position 0

Fout-ID: 45f0a180

All my graphs are showing this same error!

**Comment by przemoo83** [comment]
Hi, there's been a major update to the connector recently and there's been a cuple of breaking changes.  You will have to edit your current data source. Go to "Resource > Manage Added Data Sources"  and edit youe "GTrends" source. Next "Edit connection" and type required patameters. After you reconnect the source make sure to click "Refresh Fields" at the bottom in your "schema" view. After you've done that you would have to check your reports for missing fields and swap them with new ones.  I know it is a lot of hassle but the new verion of the connector will allow you to see more data e.g related queries and also you may edit all of the parameters inside reports which was not possible with the previous version. Hope it helps!

**Comment by juliecrampe** [comment]
Hi Przemek

Thank you so much, it helped me a lot. I would like to thank you for your incredible tool!
Dziękuję i do widzenia ☺

Kind regards
Julie Crampe
Digital Marketeer SEA
TUI Belgium

Van: Przemek <notifications@github.com>
Verzonden: dinsdag 1 december 2020 10:08
Aan: przemoo83/Google-Trends-DSC <Google-Trends-DSC@noreply.github.com>
CC: Crampe Julie <julie.crampe@tui.be>; Author <author@noreply.github.com>
Onderwerp: Re: [przemoo83/Google-Trends-DSC] Problem with the connector. (#1)


Hi, there's been a major update to the connector recently and there's been a cuple of breaking changes. You will have to edit your current data source. Go to "Resource > Manage Added Data Sources" and edit youe "GTrends" source. Next "Edit connection" and type required patameters. After you reconnect the source make sure to click "Refresh Fields" at the bottom in your "schema" view. After you've done that you would have to check your reports for missing fields and swap them with new ones. I know it is a lot of hassle but the new verion of the connector will allow you to see more data e.g related queries and also you may edit all of the parameters inside reports which was not possible with the previous version. Hope it helps!

**Comment by przemoo83** [comment]
You're welcome! Glad you like it. Powodzenia ;)
